Initialize is_old_binary
For an emsemble with a single test file, sometimes we saw this error:

<Test TestUID="UNKNOWN_UID" JoshuaSeed="420451347955434170" Ok="0" Error="FatalError"><JoshuaMessage Severity="40" Message="'TestRun' object has no attribute 'is_old_binary'"/>

With the fix, I no longer see this error with the same run with ~5k tests. Without fix, there are 3 failures
with the same error.