Fix errors when linking fdbserver on macOS due to boost::filesystem
This replaces boost::filesystem with std::filesystem.
`std::filesystem::recursive_directory_iterator` is supported since C++17
and `std::string::ends_with` is since C++20. FoundationDB is configured
to C++20.

Without this change, linking fails with:

```
[1183/1697] Linking CXX executable bin/fdbserver
FAILED: bin/fdbserver
...
Undefined symbols for architecture arm64:
  "boost::filesystem::detail::dir_itr_imp::~dir_itr_imp()", referenced from:
      encryptionAtRestPlaintextMarkerCheck() in tester.actor.g.cpp.o
      boost::filesystem::recursive_directory_iterator::~recursive_directory_iterator() in tester.actor.g.cpp.o
      boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&) (.cold.1) in tester.actor.g.cpp.o
  "boost::filesystem::detail::dir_itr_imp::operator delete(void*)", referenced from:
      encryptionAtRestPlaintextMarkerCheck() in tester.actor.g.cpp.o
      boost::filesystem::recursive_directory_iterator::~recursive_directory_iterator() in tester.actor.g.cpp.o
      boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&) (.cold.1) in tester.actor.g.cpp.o
  "boost::filesystem::detail::recursive_directory_iterator_construct(boost::filesystem::recursive_directory_iterator&, boost::filesystem::path const&, boost::filesystem::directory_options, boost::system::error_code*)", referenced from:
      boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&) in tester.actor.g.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```