While fixing the missing Jinga2 dependency, I noticed this CMake output for Sphinx;
```
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Switching to using seperate commands fixes this issue.