fixup! Fix the anonymous namaespace in RealStorageServer.actor.cpp
This is causing error:

/codebuild/output/src829114220/src/github.com/apple/foundationdb/fdbserver/ptxn/test/RealStorageServer.actor.cpp:120:221:   required from here
/codebuild/output/src829114220/src/github.com/apple/foundationdb/fdbserver/ptxn/test/RealStorageServer.actor.cpp:120:7: error: 'ptxn::test::RunStorageServerActorState<ptxn::test::RunStorageServerActor>' has a field 'ptxn::test::RunStorageServerActorState<ptxn::test::RunStorageServerActor>::partitionTransactionKnobDisabler' whose type uses the anonymous namespace [-Werror=subobject-linkage]