bindings/python: use venv to build python package
All the other uses of python in the build system already create a venv
to install their python dependencies in. This is generally needed
with modern pip, otherwise you get errors like:

> error: externally-managed-environment
> You may restore the old behavior of pip by passing
> the '--break-system-packages' flag to pip

This problem can also be avoided by creating/activating a venv
manually, before running the foundationdb cmake config, and that
does not cause problems for this cmake build to create and use
more venvs.

Also, no need to upgrade pip all the time, any remotely supported
python3 version install has a good-enough pip (good enough to
upgrade itself!)