build: googlebenchmark download/build with FetchContent
Simplify the googlebenchmark download and compile by
switching from ExternalProject_Add() with additional custom cmake
execute_process() commands, to FetchContent_Declare() + _MakeAvailable()

The motivation was to more easily and cleanly fix compile errors
on recent macOS with recent clang+libcxx, which automatically enable
warning option -Wthread-safety-analysis which is not compatible
with this library and fails the build if -Werror is enabled:

    googlebenchmark-download/googlebenchmark-src/src/mutex.h:79:40: error:
    mutex 'mut_' is still held at the end of function [-Werror,-Wthread-safety-analysis]
       79 |   void lock() ACQUIRE() { mut_.lock(); }
          |                                        ^

It seemed like the cleanest way of avoiding this build error was
to ensure -Werror is disabled for googlebenchmark, and the best
way to do that was to cleanup the googlebenchmark build.
Also remove googletest dependency by disabling googlebenchmark tests.