Statically link libcurl for the aws sdk (snowflake/release-71.2) (#8248)
* Cherry pick #8226 to snowflake/release-71.2

* Cherry pick #8248

* Limit BUILD_AWS_BACKUP to x86_64 for now

With aarch64, in the current docker image, linking curl statically doesn't work yet.

This is the diagnostic:

```
fdbclient/awssdk-build/curl/lib/strerror.c:32:6: error: #error "strerror_r MUST be either POSIX, glibc or vxworks-style"
2022-09-22 16:05:30   #    error "strerror_r MUST be either POSIX, glibc or vxworks-style"
2022-09-22 16:05:30        ^~~~~
```

The root cause is that curl's cmake feature detection logic gets
confused since it can't build binaries that execute successfully with
the link flags it wants:

```
$ cc test.c -lssl
$ ./a.out
./a.out: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Co-authored-by: Josh Slocum <josh.slocum@snowflake.com>